# Generated by Django 5.0.4 on 2024-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todoitem',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
